### ISSUE TITLE
[AuthScreen] Анимация перехода из состояния Регистрации в Авторизацию

### ISSUE THREAD

**Issue by Maksim193** [BlurCorporation/UnderWaterPhotos#5]
Подобный функционал с анимированным выезжанием кнопки реализован в методе expand на 314 строке https://github.com/Vladimir-Murashka/ARHitBalls/blob/develop/ARHitBalls/Scenes/Main/MainViewController.swift

**Comment by oknenorimAnton** [comment]
Add animated transitions buttons and textFiealds
